
export const metadata = {
  title: "Sidiq Yanuar | Homepage"
};

export default function Home() {
  return (
    <>
      <div className="text-xl">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam ratione tempora explicabo a vitae alias porro repudiandae in provident similique saepe delectus, eius cupiditate ullam eligendi doloribus quasi esse voluptatem. Vitae explicabo cum odio nemo porro totam voluptas excepturi eum, non, quibusdam et eligendi laboriosam. Qui deleniti dolore commodi et sequi odit? Iure magni aspernatur voluptatem dolores itaque, incidunt enim inventore voluptate quam explicabo iste a provident similique temporibus repellendus sit officia esse quisquam laboriosam laborum doloribus. Eum quam aliquid dolor! Perferendis debitis et repellat, dolorum, at quaerat eos suscipit aperiam fugiat aliquam reiciendis placeat voluptatum cum ducimus, rerum officiis?Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto nobis dolorum vel libero, quam officiis placeat voluptas molestias minima, laborum nostrum? Corrupti nulla sunt eos fuga dolore exercitationem et. Ea unde quibusdam, repellendus, asperiores expedita dolorem pariatur impedit aliquid voluptas iure placeat? Fugit et repudiandae consectetur molestias quis corporis accusantium necessitatibus deserunt iste impedit veniam adipisci porro deleniti quas ad maiores quibusdam eveniet, quam harum nulla nesciunt enim totam officiis nobis. Provident corporis temporibus eveniet accusantium voluptate labore nostrum. Consequatur voluptatem pariatur, obcaecati exercitationem alias, ipsam nam animi fugiat numquam placeat explicabo dolorum sed? Totam amet harum commodi culpa tempore!</div>

      <div className="text-xl">Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum expedita voluptas illo nobis quisquam laborum doloremque officia voluptate eaque beatae, voluptatibus in ducimus dignissimos cum modi, at, esse maxime tempore sint suscipit magni obcaecati ex fugiat? Sint officia, nobis praesentium possimus est nisi nulla iure. Consequatur vero dicta nisi et veniam unde possimus quidem maxime modi consectetur quisquam enim voluptatem quasi, at harum cum doloremque! Velit recusandae eligendi aspernatur ipsum voluptates saepe, ab cumque. Minima repudiandae non libero id aperiam laudantium corrupti, consequatur unde. Mollitia eos assumenda et nulla minima culpa soluta cum magnam doloribus, beatae fuga, natus aspernatur laudantium. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Labore, porro. Incidunt repudiandae numquam veniam asperiores magni impedit dolores soluta beatae vitae, dolorum enim. Est, magni. Consequatur non eaque quis perferendis fugit atque ad omnis eveniet repellat dolore at, aut hic aliquam aperiam alias officia. Corporis dolores suscipit nemo dignissimos dolore, delectus laudantium sunt laborum porro aspernatur expedita, maxime illum. Soluta magni minus, quisquam molestiae quia incidunt laborum. Doloribus reprehenderit quia, ex non dolore reiciendis sequi. Molestias, aliquam veritatis! Quibusdam exercitationem reprehenderit impedit ex. Enim minus eaque qui maxime voluptas in quam est eos quasi, blanditiis esse reprehenderit sapiente odit voluptatum. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Ipsum asperiores vel, nostrum alias quo deserunt harum dolorum commodi! Dicta ipsum ducimus magnam vel minus ea, tenetur inventore deleniti officiis porro quod saepe, dolore quis quo officia necessitatibus omnis numquam incidunt perspiciatis. Pariatur nisi quisquam laboriosam minima itaque incidunt error soluta, maiores culpa repellat corrupti corporis quis mollitia fugiat asperiores! Quidem sunt eligendi ratione magnam consequatur necessitatibus odio autem, blanditiis officiis sit laudantium, molestias officia. Dolorem laudantium et, totam quis delectus eligendi repudiandae eaque id iusto vitae culpa animi aut assumenda tempore dolores dicta, voluptatibus numquam unde asperiores reiciendis aspernatur quae!</div>
    </>
  );
}
